tailwind.config = {
            darkMode: "class",
            theme: {
                extend: {
                    "colors": {
                        "surface-container-high": "#fae4dd",
                        "tertiary-container": "#00b5c3",
                        "surface-dim": "#ebd6cf",
                        "on-error": "#ffffff",
                        "primary": "#a43d0c",
                        "error": "#ba1a1a",
                        "outline": "#8b7269",
                        "orange-deep": "#E8672F",
                        "on-tertiary": "#ffffff",
                        "secondary": "#006b55",
                        "ink-text": "#2B1B12",
                        "inverse-on-surface": "#ffede7",
                        "tertiary": "#006971",
                        "tertiary-fixed": "#88f3ff",
                        "on-tertiary-fixed": "#001f23",
                        "cream-bg": "#FFF4E8",
                        "surface-bright": "#fff8f6",
                        "primary-fixed-dim": "#ffb59a",
                        "error-container": "#ffdad6",
                        "inverse-surface": "#3a2e29",
                        "on-surface": "#241915",
                        "background": "#fff8f6",
                        "tertiary-fixed-dim": "#4dd8e7",
                        "on-secondary-fixed-variant": "#005140",
                        "border-line": "rgba(43, 27, 18, 0.12)",
                        "surface-container-highest": "#f4ded7",
                        "cream-deep": "#FFE9D3",
                        "surface-variant": "#f4ded7",
                        "on-tertiary-container": "#004146",
                        "on-secondary-fixed": "#002018",
                        "teal-deep": "#146856",
                        "on-primary-container": "#6b2100",
                        "primary-fixed": "#ffdbcf",
                        "outline-variant": "#dec0b6",
                        "on-surface-variant": "#57423a",
                        "on-tertiary-fixed-variant": "#004f56",
                        "on-error-container": "#93000a",
                        "surface": "#fff8f6",
                        "surface-container": "#ffe9e2",
                        "surface-container-lowest": "#ffffff",
                        "accent-yellow": "#FFC24B",
                        "on-background": "#241915",
                        "on-primary-fixed": "#380d00",
                        "surface-container-low": "#fff1ec",
                        "surface-tint": "#a43d0c",
                        "secondary-container": "#94f5d6",
                        "primary-container": "#ff7f4c",
                        "on-secondary-container": "#00725b",
                        "on-primary": "#ffffff",
                        "ink-soft": "#6B5646",
                        "inverse-primary": "#ffb59a",
                        "secondary-fixed-dim": "#78d8ba",
                        "on-secondary": "#ffffff",
                        "on-primary-fixed-variant": "#802a00",
                        "secondary-fixed": "#94f5d6"
                    },
                    "borderRadius": {
                        "DEFAULT": "0.25rem",
                        "lg": "0.5rem",
                        "xl": "0.75rem",
                        "full": "9999px"
                    },
                    "spacing": {
                        "margin-desktop": "2.5rem",
                        "margin-mobile": "1rem",
                        "md": "1rem",
                        "gutter": "1rem",
                        "sm": "0.5rem",
                        "lg": "1.5rem",
                        "xs": "0.25rem",
                        "xl": "2rem"
                    },
                    "fontFamily": {
                        "body-md": ["Plus Jakarta Sans"],
                        "button-text": ["Plus Jakarta Sans"],
                        "display-md": ["Plus Jakarta Sans"],
                        "display-lg": ["Plus Jakarta Sans"],
                        "body-lg": ["Plus Jakarta Sans"],
                        "display-xl": ["Plus Jakarta Sans"],
                        "label-mono": ["Space Mono"]
                    },
                    "fontSize": {
                        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
                        "button-text": ["16px", { "lineHeight": "1", "fontWeight": "600" }],
                        "display-md": ["28px", { "lineHeight": "1.3", "fontWeight": "600" }],
                        "display-lg": ["36px", { "lineHeight": "1.2", "fontWeight": "700" }],
                        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
                        "display-xl": ["48px", { "lineHeight": "1.1", "fontWeight": "800" }],
                        "label-mono": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "700" }]
                    }
                }
            }
        }